Merge asp-net-mvc branch to main branch
Catmanaha/TradingApp pull request #5
Opened 2024-01-19 14:40 UTC by Catmanaha

2024-01-23 20:47 UTC, ElnurMustafayev commented
Нет .sql файлов

Как проверять?)

2024-01-23 20:49 UTC, ElnurMustafayev requested changes
1. В PR появился конфликт. Нужно его решить
2. В проекте нет .sql creational файлов. Как проверять?)

2024-01-31 17:18 UTC, ElnurMustafayev approved these changes
с репозиториями задумка получилась интересной, но там тоже есть, над чем поработать.

А так недочётов хватает. Оценка 8

2024-01-31 17:18 UTC, ElnurMustafayev commented on TradingApp/Program.cs
> +string? connectionString = builder.Configuration.GetConnectionString("TradingAppDb");
Имей в виду, что в таком случае не будет возможности динамически изменять строку подключения во время работы приложения на сервере. Всё-таки было бы лучше написать это прямо в `AddScoped` методе

2024-01-31 17:18 UTC, ElnurMustafayev commented on TradingApp/Program.cs
> +ArgumentNullException.ThrowIfNull(connectionString);
хорошо, что выкидываешь ошибку, но для таких критических ситуаций лучше выкидывать ошибки с детальной информацией, чтобы легко и быстро понять, что именно пошло не так, например:

Couldn't find connection string by key 'TradingAppDb' in appsettings.json file

2024-01-31 17:18 UTC, ElnurMustafayev commented on TradingApp/Program.cs
> +    pattern: "{controller=Stock}/{action=GetAll}");
Теперь для всех endpoint-ов framework будет пытаться подставить вместо controller-а `Stock`, а вместо всех непрописанных action-ов почему-то `GetAll`. 
Лучше дефолтные вещи делать(оставлять) **максимально обобщенными**

2024-01-31 17:18 UTC, ElnurMustafayev commented on TradingApp/Repositories/Base/Repositories/IStockRepository.cs
Красиво получилось!

2024-01-31 17:18 UTC, ElnurMustafayev commented on TradingApp/Repositories/StockSqlRepository.cs
> +    public async Task<int> CreateAsync<Stock>(Stock stock)
чем писать реализации в таком виде (`CreateAsync<Stock>`) лучше было бы сделать сами интерфейсы шаблонными:

`IGetAll<T>`, `ICreateAll<T>`

В таком случае методы сами не будут уже шаблонными

2024-01-31 17:18 UTC, ElnurMustafayev commented on TradingApp/Controllers/StockController.cs
> +    public async Task<IActionResult> Create(StockDto stock)
Тут можно было, как вариант, все нижние ошибки собрать в какой-то лист и вернуть всё полностью пользователю. А то так, получается, решив одну проблему, пользователю будет выходить следующая и т.д. Немного недружелюбно получается

2024-01-31 17:18 UTC, ElnurMustafayev commented on TradingApp/Controllers/StockController.cs
> +            return BadRequest("Dont leave the market capacity field empty");
ошибки все однотипные, можно было бы придумать через throw, try, catch конструкцию. Или же прописать ExceptionHandler (Middleware), который обрабатывает как-то ArgumentException-ы

2024-01-31 17:18 UTC, ElnurMustafayev commented on TradingApp/Controllers/StockController.cs
> +    public StockController(ISqlRepository<Stock> repository)
как так получилось, что ты мне в PR отправляешь ветку с нерабочим кодом? Ты его запускал перед push-ем? 
Типа ISqlRepository нет в проекте

2024-01-31 17:18 UTC, ElnurMustafayev commented on TradingApp/Models/Stock.cs
>      public string? MarketCap { get; set; }
Это должно быть числом, а не строкой, в которой еще пишется единица счисления. С такими данными никаких вычислений потом невозможно будет сделать

2024-01-31 17:18 UTC, ElnurMustafayev commented on TradingApp/Models/User.cs
тип, который не нужен - не должен был выходить в remout

2024-01-31 17:18 UTC, ElnurMustafayev commented on TradingApp/Models/UserStock.cs
ненужный класс

2024-01-31 17:18 UTC, ElnurMustafayev commented on TradingApp/Views/Stock/GetAll.cshtml
> +  <div class="container">
тут должен был быть тег table со всеми его внутренними тегами. Верстать только дивами - очень плохая практика

2024-01-31 17:18 UTC, merged

2024-01-31 17:38 UTC, Catmanaha commented on TradingApp/Controllers/StockController.cs
> +    public StockController(ISqlRepository<Stock> repository)
Да, наверно я что-то не так запушыл